config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :cars do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create ]
  end
  resources :users, only: [:show]
  resources :search, only: [:index]
  resources :bookings, only: [:index, :show]
  resources :reviews, only: [:edit, :update, :destroy]
end

app/models/booking.rb
class Booking < ApplicationRecord
  belongs_to :user
  belongs_to :car
  validates :price, presence: true
end

app/controllers/bookings_controller.rb
class BookingsController < ApplicationController
  before_action :authenticate_user!
  def index
    @bookings = Booking.where(user: current_user)
  end

  def show
    @booking = Booking.find(params[:id])
    @owner = @booking.car.user
    @renter = @booking.user
    @car = @booking.car


    @markers = @owner.geocode do |dir|
      {
        lat: dir.latitude,
        lng: dir.longitude
    }
    end
  end

  def new
    @booking = Booking.new
    @car = Car.find(params[:car_id])
  end

  def create
    @car = Car.find(params[:car_id])
    booking = Booking.new(booking_params)
    booking.car = @car
    booking.user = current_user
    booking.price = params[:booking][:totalprice].to_i
    if booking.save!
      redirect_to booking_path(booking)
    else
      render :new
    end
  end

  private

  def booking_params
    params.require(:booking).permit(:user_id, :car_id, :initial_date, :final_date)
  end

end

app/views/bookings/index.html.erb
<div class="container">
    <h1 class="text-center">Bookings</h1>
    <% @bookings.each do |booking| %>
        <div class="bookings-element card-product">
            <%= cl_image_tag(booking.car.photo.key, height:150, width: 200, crop: :fill) %>
            <div class="book-info">
                <h5><%= booking.car.info %></h5>
                <p>Owner: <%= booking.car.owner %></p>
                <p>From :<%= booking.initial_date.strftime("%B %d, %Y") %> to <%= booking.final_date.strftime("%B %d, %Y") %></p>
                <%= link_to booking_url(booking), class:"white-text" do%>
                    <button type="button" class='click-dark my-3'>See more</button>
                <% end %>
            </div>
        </div>
    <% end %>
</div>

app/views/bookings/new.html.erb
<%= simple_form_for [@car, @booking] do |f| %>
<div class="form-inputs col-md-4 offset-md-4">
  <%= f.input :initial_date, readonly: 'true', placeholder: 'Start Date'%>
  <%= f.input :final_date, readonly: 'true', placeholder: 'End Date' %>
  <%= f.button :submit, class: "btn-primary" %>
<% end %>
</div>

app/views/bookings/show.html.erb
<h1 class='text-center m-3'>Booking</h1>
<div class="card-center mb-3" style="max-width: 1080px;">
  <div class="row no-gutters">
    <div class="col-md-4 ">
     <%= cl_image_tag(@booking.car.photo.key, :width => 350, :height => 250, :crop => :fill) %>
    </div>
    <div class="col-md-8">
      <div class="card-body">
        <h3 class="card-title"><%= @booking.car.info %></h3>
        <p class="card-text">Owner: <strong><%= @car.owner %></strong></p>
        <p class="card-title">From: <%= @booking.initial_date.strftime("%B %d, %Y") %> to <%= @booking.final_date.strftime("%B %d, %Y") %></p>
        <p class="card-text"><small class="text-muted">Price: £<%= @booking.price %></small></p>
        <div class="d-flex justify-content-between">
          <%= link_to car_path(@booking.car), class:"white-text" do%>
            <button type="button" class='click-dark'>Car site</button>
          <% end %>
          <button type='button' class='btn-animate mb-3'><span><%=link_to "Return", bookings_path, class:"white-text"%> </span></button>
        </div>
      </div>
    </div>
  </div>  
</div>

<div class="card-center-map mb-3" style="max-width: 1080px;">
  <div class="no-gutters">
    <div class="text-center">
      <div class="card-body pb-1 bg-dark">
        <h2 class="card-title text-white"><%= @car.user.address %></h2>
      </div>
    </div>
    <div class="col-md-12">
      <div id="map"
      style="width: 100%;
      height: 300px;
      border-radius: 0 0 15px 15px"
      data-markers="<%= @markers.to_json %>"
      data-mapbox-api-key="<%= ENV['MAPBOX_API_KEY'] %>"></div>
    </div>
  </div>
  
</div>