config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :cars do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create ]
  end
  resources :users, only: [:show]
  resources :search, only: [:index]
  resources :bookings, only: [:index, :show]
  resources :reviews, only: [:edit, :update, :destroy]
end

app/views/pages/Index.html.erb
  <h2><strong>Cars List</strong></h2>
  <p><%= link_to "Create Rental Car", new_car_path %><p>
  <% @cars.each do |car| %>
    <h1><%= car.name %></h1>
    <h1><%= car.description %></h1>
    <h1><%= car.price %></h1>
    <h1><%= car.availabilty? %></h1>
    <p><%= link_to "for more detail click here", car_path(car) %><p>
  <% end %>

app/views/pages/home.html.erb
<div class="flex-container justify-content-center align-items-start" >
  <div class='card-home'>
    <div class='intro-text'>
      <h1 class="font-text">Search for luxury cars</h1>
    </div>
    <div class="search-choices">
      <div class="search-choices-background">
        <%= form_tag cars_url, method: :get, class:"search-form" do  %>
          <div class="search-choice-margins">
            <span class="search-choice-title">Brand</span>
            <div class="search-choice-bar">
              <%= text_field_tag :brand, nil, class: "search-input", placeholder: "Find brand.." %>
            </div>
          </div>
          <div class="search-choice-margins">
             <span class="search-choice-title">Type</span>
            <div class="search-choice-bar">
              <select id="kind" name="kind" class="search-input">
                <option value="Any">Any</option>
                <option value="Hybrid">Hybrid</option>
                <option value="Electric">Electric</option>
                <option value="Petrol">Petrol</option>
                <option value="Diesel">Diesel</option>
                <option value="Hybrid">Hybrid</option></select>
            </div>
          </div>
          <div class="search-choice-margins">
             <span class="search-choice-title">Transmission</span>
            <div class="search-choice-bar">
              <select id="transmission" name="transmission" class="search-input">
                <option value="Any">Any</option>
                <option value="Manual">Manual</option>
                <option value="Automatic">Automatic</option></select>
            </div>
          </div>
          <div class="src-animate-center">
            <%= submit_tag "Search", class: "btn click-dark-home" %>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</div>

app/views/pages/show.html.erb
<%= link_to "return to list", cars_path %>

<h1><%= @car.name %></h1> <h1>CAR IMAGE</h1>
<h1><%= @car.model %></h1>
<h1><%= @car.description %></h1>
<h1><%= @car.price %></h1>
<h1><%= @car.type %></h1>

<%= link_to "Book now!", Book_car_path(@car.id) %>

<% @car.reviews.each do |review|%>
    <h1><%= review.name %></h1> | <h1><%= review.rating %></h1>
    <p><%= review.description %></p>
<% end %>