config/routes.rb
Rails.application.routes.draw do
  root to: 'pages#home'
  devise_for :users
  resources :cars do
    resources :bookings, only: [:new, :create]
    resources :reviews, only: [:new, :create ]
  end
  resources :users, only: [:show]
  resources :search, only: [:index]
  resources :bookings, only: [:index, :show]
  resources :reviews, only: [:edit, :update, :destroy]
end

app/models/car.rb
class Car < ApplicationRecord
  has_many :bookings, dependent: :destroy
  has_many :reviews,dependent: :destroy
  has_one_attached :photo
  belongs_to :user
  KINDS = ['Petrol', 'Diesel', 'Electric', 'Hybrid']
  TRANS = ['Manual', 'Automatic']
  validates :model, presence: true
  validates :brand, presence: true
  validates :kind, presence: true, inclusion: {in: KINDS}
  validates :price, presence: true
  validates :description, presence: true
  validates :doors, presence: true, inclusion: {in: (1..5).to_a}
  validates :transmission, presence: true, inclusion: {in: TRANS}

  include PgSearch::Model
  pg_search_scope :search_by_everything,
    against: [ :brand, :model, :doors, :year, :transmission, :kind ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    pg_search_scope :search_by_not_kind,
    against: [ :brand, :model, :doors, :year, :transmission],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    pg_search_scope :search_by_not_transmission,
    against: [ :brand, :model, :doors, :year, :kind ],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }

    pg_search_scope :search_by_not_both,
    against: [ :brand, :model, :doors, :year],
    using: {
      tsearch: { prefix: true } # <-- now `superman batm` will return something!
    }
  
  def info
    "#{self.brand.capitalize} #{self.model}, #{self.kind.downcase}."
  end

  def owner
    self.user.username
  end

  include PgSearch
  pg_search_scope :search, against: [:brand, :model], using: {tsearch: {prefix: true, any_word: true}}
end

app/controllers/cars_controller.rb
class CarsController < ApplicationController
  before_action :define_arrays, only: [:edit, :new]
  before_action :get_car, only: [:show, :edit, :update, :destroy]
  def index
    @cars = Car.all
    if params[:brand].present? || params[:model].present? || params[:doors].present? || params[:year].present?
      if params[:transmission] == "Any" && params[:kind] == "Any"
        @cars = Car.search_by_not_both("#{params[:brand]} #{params[:model]} #{params[:doors]} #{params[:year]}")
      elsif params[:transmission] == "Any"
          @cars = Car.search_by_not_transmission("#{params[:brand]} #{params[:model]} #{params[:doors]} #{params[:year]} #{params[:kind]}")
      elsif params[:kind] == "Any"
        @cars = Car.search_by_not_kind("#{params[:brand]} #{params[:model]} #{params[:doors]} #{params[:year]} #{params[:transmission]}")
      else
        @cars = Car.search_by_everything("#{params[:brand]} #{params[:model]} #{params[:doors]} #{params[:year]} #{params[:transmission]} #{params[:kind]}")
      end
    elsif params[:transmission] != "Any" || params[:kind] != "Any"
      if params[:kind].present? && params[:kind] != "Any"
        @cars = Car.search_by_not_transmission("#{params[:brand]} #{params[:model]} #{params[:doors]} #{params[:year]} #{params[:kind]}")
      elsif params[:transmission].present? && params[:transmission] != "Any"
        @cars = Car.search_by_not_kind("#{params[:brand]} #{params[:model]} #{params[:doors]} #{params[:year]} #{params[:transmission]}")
      end
    end
  end

  def show
    @car = Car.find(params[:id])
    @booking = Booking.new

    @can_review = ->{
      return false unless signed_in?
      bookings = Booking.where(user: current_user);
      if bookings
        bookings.each do |booking|
          return true if booking.final_date < DateTime.now.to_date
        end
      end
      false
    }.call

  end

  def new
    @car = Car.new
  end

  def create

    @car = Car.new(car_params)
    @car.user = current_user
    if @car.save!
      redirect_to car_path(@car)
    else
      render :new
    end
  end

  def edit
  end

  def update
    @car.update(car_params)
    redirect_to car_url(@car)
  end

  def destroy
    car = Car.find(params[:id])
    car.destroy
    redirect_to cars_path
  end
  private

  def car_params
    params.require(:car).permit(:description, :price, :model, :kind, :brand, :photo)
  end

  def define_arrays
    @kinds = ['Petrol', 'Diesel', 'Electric', 'Hybrid']
    @trans = ['Manual', 'Automatic']
  end

  def get_car
    @car = Car.find(params[:id])
  end
end

app/views/cars/edit.html.erb
<%= simple_form_for @car do |f| %>
  <div class="form-inputs col-md-4 offset-md-4">
    <%= f.input :brand, placeholder: 'Brand' %>
    <%= f.input :model, placeholder: 'Model' %>
    <%= f.input :kind, :collection => @kinds %>
    <%= f.input :price, placeholder: 'Price' %>
    <%= f.input :description, placeholder: 'Tell us a little bit about your car!' %>
    <%= f.submit "Create car!", class: "btn btn-primary" %>
  </div>
<% end %>

app/views/cars/index.html.erb
<div class="container">
  <h1 class="text-center">Our cars</h1>
  <div class="text-center car-grid">
    <% @cars.each do |car| %>
      <div class='index-card'>
        <div class='index-card-top' style= "background-image: url('<%= cl_image_path(car.photo.key, height:300, width:400, crop: :fill); %>')">
          <div class="background-image">
            <div class='background-image-safety'></div>
            <div class='adding-angle'>
              <svg class='index-angle' viewBox='0 0 235 25' preserveAspectRation='xMinYMax slice'>
                <polygon points="235 0 235 25 0 25"></polygon>
              </svg>
            </div>
          </div>
        </div>
        <div class='car-info text-center'>
          <div class="flex-grow-1">
            <h4 class='car-title'><%= car.brand %> <%= car.model %></h4>
            <div class='equipment'>
              <ul>
                <div class='d-flex list-box'>
                  <div>
                    <div class='list-spacing'>
                     <li title='transmission'><i class="fas fa-car-alt"></i> <%= car.transmission %></li>
                    </div>
                    <div class='list-spacing'>
                      <li title='year'><i class="far fa-calendar-alt"></i> <%= car.year%></li>
                    </div>
                  </div>
                  <div>
                    <div class='list-spacing'>
                      <li title='seats'><i class="far fa-user"></i> <%= car.seats %></li>
                    </div>
                    <div class='list-spacing'>
                      <li title='doors'><i class="fas fa-pager"></i> <%= car.doors %></li>
                    </div>
                  </div>
                </div>
              </ul>
            </div>
          </div>

          <div class="positioning">
            <%= link_to car_url(car), class:"white-text" do%>
            <button type="button" class='click-dark mb-3'>See more</button>
            <% end %>
          </div>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/cars/new.html.erb
<%= simple_form_for @car do |f| %>
<div class="form-inputs col-md-4 offset-md-4">
    <%= f.input :brand, placeholder: 'Brand' %>
    <%= f.input :model, placeholder: 'Model' %>
    <%= f.input :kind, collection: @kinds %>
    <%= f.input :price, placeholder: 'Price' %>
    <%= f.input :transmission, collection: @trans %>
    <%= f.input :doors, placeholder: 'Doors' %>
    <%= f.input :year, placeholder: 'Year' %>
    <%= f.input :description, placeholder: 'Tell us a little bit about your car!' %>
    <%= f.input :photo, as: :file %>
    <%= f.submit "Create car!", class: "btn btn-primary" %>
<% end %>
</div>

app/views/cars/show.html.erb
<div class="container car-show-font py-3">
  <div class="row">
    <div class="card mb-2">
      <div class="row">
        <div class="col">
          <div class="car-show-info">
            <div class="card-title-show justify-content-between">
              <h1><%= @car.brand %> <%= @car.model %></h1>
            </div>
            <div class="col car-show-image">
              <%= cl_image_tag(@car.photo.key, height:350, width: 530, crop: :fill) %>
            </div>
            <div class="col">
              <div class="card-body">
              </div>
            </div>
          </div>
        </div>


        <div class="col-auto">
          <div class="car-show-info">
            <div id="booking-form" class="booking-form-show flex-grow-1">
              <%= simple_form_for [@car, @booking] do |f| %>
                <h2><%= @car.price%>£ / day</h2>
                <div class="form-inputs-show">
                  <%= f.input :initial_date, readonly: 'true', placeholder: 'Start Date', start_year: Date.today.year, id: 'start'%>
                  <%= f.input :final_date, readonly: 'true', placeholder: 'End Date', id: 'end' %>
                  <%= f.hidden_field :totalprice, id: 'hidden', value: @car.price %>
                  <h5 id="price" data-price=<%= @car.price %> >Total price: <%= @car.price %> £</h5>
                  <%= f.button :submit, class: "btn-primary" %>
                </div>
              <% end %>
            </div>
          </div>
        </div>
      </div>
    <div class="card-information-show-car">
      <div class=" row car-show-info-details justify-content-around">
        <div class="col">
          <p><strong>Car Details</strong></p>
          <p class="card-text">- Owner: <%= @car.user.name %></p>
          <p class="card-text">- Description: <%= @car.description %></p>
          <p class="card-text">- <%= @car.brand %></p>
          <p class="card-text">- <%= @car.kind %></p>
          <p class="card-text">- <%= @car.transmission %></p>
          <p class="card-text">- <%= @car.year %></p>
        </div>
        <div class="col">
          <p><strong>Equipment, seats and luggage</strong></p>
          <p>- Air conditioning available</p>
          <p>- <%= @car.doors %> Doors</p>
          <p>- <%= @car.seats %> Seats</p>
        </div>
      </div>
    </div>
  <div class="card bg-light mb-3">
    <div class="card-header">
      <p><strong>Reviews:</strong></p>
      <% if @can_review %>
      <p><%= link_to "Create a Review", new_car_review_path(@car) %><p>
      <% end %>
    </div>
      <% @car.reviews.each do |review| %>
        <div class="review d-flex border-top">
          <div class="review-picture border-right d-flex align-item-center justify-content-center">
            <% if review.user.photo.attached? %>
              <%= cl_image_tag current_user.photo.key, class: "avatar review-image" %>
            <% else %>
              <%= image_tag "pp.png", class: "avatar review-image"%>
            <% end %>
          </div>
          <div class="review-content flex-grow-1">
            <div class="card-text">
              <i class ="far fa-comments"></i> <%= review.content %>
            </div>
            <div class="review-stars">
              <% review.rating.times do %>
                <i class="fas fa-star yellow"></i>
              <% end %>
              <% (5 - review.rating).times do %>
                <i class="far fa-star yellow"></i>
              <% end %>
            </div>
          </div>
          <div class="review-options">
            <% if (review.user == current_user) %>
              <i class="fas fa-pencil-alt"><%= link_to "Edit my review", edit_review_path(review) %></i>
              <br>
              <i class="fas fa-trash"><%= link_to "Delete my review", review_path(review), method: "delete" %></i>
            <% end %>
          </div>
        </div>
    <% end %>
  </div>
</div>

<script>
  const dates = document.querySelectorAll('.form-inputs-show .form-group');
  const price = document.querySelector('#price');
  const rent = document.getElementById("hidden");
  dates.forEach((field) => {
      field.addEventListener('click', (event) => {
          const dayprice = parseInt(price.dataset.price);
          let startyear = document.querySelector('#booking_initial_date_1i').selectedOptions[0].innerHTML
          let startmonth = document.querySelector('#booking_initial_date_2i').selectedOptions[0].innerHTML
          let startday = document.querySelector('#booking_initial_date_3i').selectedOptions[0].innerHTML
          let startdate = new Date(`${startyear}-${startmonth}-${startday}`);
          let endyear = document.querySelector('#booking_final_date_1i').selectedOptions[0].innerHTML
          let endmonth = document.querySelector('#booking_final_date_2i').selectedOptions[0].innerHTML
          let endday = document.querySelector('#booking_final_date_3i').selectedOptions[0].innerHTML
          let enddate = new Date(`${endyear}-${endmonth}-${endday}`);
          let days = (enddate-startdate)/(1000 * 3600 * 24);
          let finalprice = (days+1)*dayprice
          price.innerHTML = `Total price: ${finalprice} £`;
          rent.value = finalprice;
      });
  });
</script>